version: "3.7"

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres/:/postgres-init-data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=flowrspot
      - POSTGRES_PASSWORD=flowrspot
      - POSTGRES_DB=flowrspot
  sonarqube:
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"